language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-format-5.0
      - g++-6
      - xsltproc

install:
  - export CC=gcc-6
  - export CXX=g++-6
  - make build

script: make test-py
