language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-format-5.0
      - g++-6
      - xsltproc

install:
  - export CC=gcc-6
  - export CXX=g++-6
  - make build
  - python -m pip install -r requirements.txt
  - python -m pip install -e .
  - git clone -b interchange https://github.com/Xilinx/RapidWright.git $HOME/RapidWright
  - git clone https://github.com/capnproto/capnproto-java.git $HOME/capnproto-java

script:
  - CAPNP_PATH=$HOME/capnproto-java/compiler/src/main/schema/ INTERCHANGE_SCHEMA_PATH=$HOME/RapidWright/interchange make test-py
  - make format
  - test $(git status --porcelain | wc -l) -eq 0 || { git diff; git status --porcelain; false; }
